let name = "Name-Manit Kumar";
console.log(name);
let age = "Age- 22 ";
console.log(age);
let favfood = "Favourite Food - Cheese";
console.log(favfood);
let scname = "School Name - L I C Kelanpur";
let hobb = "Hobby-Listening Music";
console.log(scname);
console.log(hobb);
let home = "Home-Bijnor";
console.log(home);